### PR TITLE
Mini fix build

### PR DESCRIPTION
**Pull request by frheault**
Small mistake due to inverted condition that was making singularity crash.
Simply fix for that, now fully tested with singularity.

### CODE REVIEW

**Review by MarioOcampo — COMMENTED** [review]
After testing it. 
- Default  `build_dir=None`, in single executions and multiples executions (changing the model), OK 
- When` build_dir not None`, for a **single execution**, OK
If the folder does not exist, it is created.
If the folder exists and it is empty, the files are created correctly.
If the folder exists and it is not empty, and an error is shown and the execution is stopped.

- When` build_dir not None`, **multiple executions** (in the same session of python) are not supported, and a warning is displayed. Only the first compilation and dictionary creation is performed, the following ones do not change the files, this may produce unexpected/wrong behavior and results.

**Comment by frheault** [comment]
@daducci So is that appropriate behavior?

**Comment by daducci** [comment]
I think this is not a problem for the normal usage (ie without specifying the build_dir). @MarioOcampo can you confirm? Could this be an issue for your application in a cluster environment (running COMMIT by changing the model in the same python instance, within a build_dir)? Sorry but I cannot test that

**Comment by MarioOcampo** [comment]
The normal use (without specifying the build_dir) is OK, the file is updated as it is in the actual version. 
Changing the model in the same python instance using build_dir is not supported, the PR displays a warning about this. Only the first compilation is executed correctly.

**Comment by frheault** [comment]
I think this is clearer and safer than before. It should work fine unless someone wants it to fail and ignore warning.

**Pull request merged**
