### PR TITLE
add peak affine flag for rotation in trk2dictionary, COMMIT_debugger …

### PR DESCRIPTION
**Pull request by steso**
I added a new flag to trk2dictionary in order to be able to handle rotations in the affine header of the peak-file if orientations are stored in world-coordinates (as e.g. if extracted from MRtrix) instead of voxel-coordinates (as from dipy). An additional option is also added to the COMMIT_debugger and I changed the documentation accordingly.

### CODE REVIEW

**Comment by daducci** [comment]
@barakovic , if you can confirm that these latest modifications solved the bug, we can then merge the PR! Thanks guys for this fix

**Comment by barakovic** [comment]
@steso can you delete the `trk2dictionary.cpp` file? Otherwise doesn't compile correctly.

**Comment by steso** [comment]
please try again

**Comment by daducci** [comment]
Closes #22

**Pull request merged**
