### PR TITLE
remove x_map, normalize volume fractions maps to 1, update demo Getting Started 

### PR DESCRIPTION
**Pull request by barakovic**
`x_map` is redundant.

### CODE REVIEW

**Comment by barakovic** [comment]
If we calculate the sum of the three maps IC + EC + ISO we get a map with an histogram close to 1. This test was done on the 'Getting started' demo.
compartment_all_histogram2

**Comment by barakovic** [comment]
With the last commit we normalize the sum of IC + EC + ISO maps to 1, like in the procedure of  `AMICO`.

compartment_allf_histogram

This normalization has almost no influence when we analyze the whole brain IC, EC and ISO maps.

Left IC before, right IC now 
ic

Left EC before, right EC now
ec

Left ISO before, right ISO now 
iso

**Comment by gabknight** [comment]
thx @barakovic . I guess it does make sense to spread proportionally the fitting error to IC, EC and ISO with a normalization. Can you see times where wouldn't want that normalization? If yes better put a Boolean parameter for it.

**Comment by barakovic** [comment]
I added the Boolean parameter `doNormalizeMaps`. The default parameter is True.

I updated the demo 'Getting Started' taking into account the rotation of the peaks with the affine.

**Comment by daducci** [comment]
Can we set the default value to False? This way we don't break backward compatibility

**Comment by daducci** [comment]
I think it is good. The only "problem" is that this PR addresses different issues, not one specific only, so in the future it could be difficult to track down any issue related to things changed within this PR. What do you think?

**Comment by gabknight** [comment]
Maybe clarify the name of the PR, including all change made.  
The commit messages are clear, so specific changes to files would be trackable in the future.

**Comment by barakovic** [comment]
True @daducci, I agree. The only way of doing in this case is to delete the PR and create 3 small PR. Should be useful to have a feature in `git` that does that automatically, at least for modifications of different files.

**Comment by gabknight** [comment]
thanks @barakovic

**Comment by daducci** [comment]
Shall this close #27??

**Comment by barakovic** [comment]
For the #27 we should check how we generated the tractography. It is possible that exist an error in the orientation if the affine was not considered. If it was done with mrtrix with the original bvals and bvecs and the option -fslgrad then everything is ok. If it was done with mrtrix with the grad scheme that we create with AMICO, which not consider the affine, and the option -grad, then there is probably an error of rotation in the peaks and in the tractography.

**Pull request merged**
